version: '3.8'
services:
  web-todo:
    image: web-todo
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:80
    networks:
      - overlay
networks:
  overlay: